# Generated by Django 3.2.4 on 2021-06-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('datafile', models.JSONField()),
                ('up_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
