# Generated by Django 3.2.4 on 2021-06-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='title',
        ),
    ]
