# Generated by Django 3.2.4 on 2021-06-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_data_detailfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='detailfile',
            field=models.JSONField(null=True),
        ),
    ]
