# Generated by Django 3.2.4 on 2021-06-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20210605_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('xcols', models.CharField(max_length=500, null=True)),
                ('ycol', models.CharField(max_length=200, null=True)),
                ('testsize', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('dataid', models.IntegerField(null=True)),
            ],
        ),
    ]
